### ISSUE TITLE
Move to GLM v3.0

### ISSUE THREAD

**Issue by jzwart** [DOI-USGS/lake-temperature-process-models-old#6]
Eventually we should switch to running [GLM v3.0](http://aed.see.uwa.edu.au/research/models/GLM/latest_release.html) (and associated [paper](https://www.geosci-model-dev.net/12/473/2019/)) given there are some bug fixes and process improvements. This might create some issues with model input / output if `nml` file formats are different and if process representation affects predictions. We should have a test for several lakes between GLM v3.0 and GLM v2.4 prior to committing to GLM v3.0

**Comment by jordansread** [comment]
Now we've made the switch, but haven't done a comprehensive evaluation of uncalibrated performance.

**Comment by jordansread** [comment]
also completed in #21
